# 部署静态内容到GitHub Pages的简单工作流程
名字：将静态内容部署到Pages

在输入：
  # 在针对默认分支的推送触发
  推:
    分支：["main"]

  # 允许您从操作选项卡手动运行此工作流程
  工作流触发输入：

# 设置 GITHUB_TOKEN 的权限以允许部署到 GitHub Pages
权限：
  目录:   目录：阅读
  页:   页数：写
  id令牌：   id令牌：写

# 仅允许一个并发部署，跳过在进行中的运行和最新排队之间的排队运行。
# 但是，请不要取消正在进行的运行，因为我们希望允许这些生产部署完成。
并发：
  组： "页面"
  取消进行中： false

工作：
  # 单个部署作业，因为我们只是进行部署
  部署:
    环境：
      名称:       名称: github-pages
      url:       url: ${{ steps.deployment.outputs.page_url }}{{ steps.deployment.outputs.page_url }}
    runs-on:     运行于：ubuntu-latest
    steps:
      - name:       - 名称：结账
        uses:         用途：actions/checkout@v4
      - name:       - 名称: 设置页面
        uses:         使用: actions/configure-pages@v5
      - name:       - name: 上传工件
        用途：actions/upload-pages-artifact@v3
        与：
          # 上传整个仓库
          路径: ''
      - 名字: 部署到GitHub Pages
        id： 部署
        用途：actions/deploy-pages@v4
